import { events } from './events.js';

// Event catalog. Compact rows expand into frozen objects at runtime
// for the public RLT.events.catalog / .byCategory tables.
//
// Row shape:
//   [name, category, shape, livePhases, stability, since, desc, subscriptionGroup?]

const LR = ['live', 'replay'];
const LRPC = ['live', 'replay', 'paused', 'countdown'];

const catalogData = [
  [
    'UpdateState',
    'tick',
    'matchstate',
    LRPC,
    'stable',
    '1.0',
    'Match snapshot at PacketSendRate.',
  ],
  [
    'GoalScored',
    'scoring',
    'goal',
    LR,
    'stable',
    '1.0',
    'Scorer + assister + last touch + impact.',
  ],
  [
    'BallHit',
    'play',
    'ballhit',
    ['live'],
    'stable',
    '1.0',
    'Ball touched. Pre/post speed and location.',
  ],
  ['CrossbarHit', 'play', 'crossbar', ['live'], 'stable', '1.0', 'Ball hit a crossbar.'],
  [
    'StatfeedEvent',
    'stat',
    'statfeed',
    LR,
    'stable',
    '1.0',
    'Player earned a stat (demo, save, epic save, etc).',
  ],
  [
    'ClockUpdatedSeconds',
    'play',
    'clock',
    ['live', 'countdown'],
    'stable',
    '1.0',
    'Match clock changed by ≥1 second.',
  ],
  [
    'MatchCreated',
    'lifecycle',
    'match',
    '*',
    'stable',
    '1.0',
    'All teams replicated; lobby ready.',
  ],
  ['MatchInitialized', 'lifecycle', 'match', '*', 'stable', '1.0', 'First countdown started.'],
  ['CountdownBegin', 'lifecycle', 'match', '*', 'stable', '1.0', 'Round countdown began.'],
  [
    'RoundStarted',
    'lifecycle',
    'match',
    '*',
    'stable',
    '1.0',
    'Active gameplay started (countdown ended).',
  ],
  ['MatchPaused', 'lifecycle', 'match', '*', 'stable', '1.0', 'Match paused by an admin.'],
  ['MatchUnpaused', 'lifecycle', 'match', '*', 'stable', '1.0', 'Match resumed.'],
  ['GoalReplayStart', 'replay', 'match', '*', 'stable', '1.0', 'Goal replay began.'],
  [
    'GoalReplayWillEnd',
    'replay',
    'match',
    '*',
    'stable',
    '1.0',
    'Ball exploded during replay (fires only if not skipped).',
  ],
  ['GoalReplayEnd', 'replay', 'match', '*', 'stable', '1.0', 'Goal replay ended.'],
  [
    'MatchEnded',
    'lifecycle',
    'matchend',
    '*',
    'stable',
    '1.0',
    'Match decided. Has WinnerTeamNum.',
  ],
  ['PodiumStart', 'lifecycle', 'match', '*', 'stable', '1.0', 'Game entered podium state.'],
  ['MatchDestroyed', 'lifecycle', 'match', '*', 'stable', '1.0', 'Player left the match.'],
  [
    'ReplayCreated',
    'lifecycle',
    'match',
    '*',
    'stable',
    '1.0',
    'Match-history replay loaded (NOT goal replays).',
  ],
  [
    '_MatchStarted',
    'lifecycle',
    'match-started',
    '*',
    'provisional',
    '1.3',
    'First time a new matchGuid lands in Countdown / Live. The "new match has begun" signal — use it to reset per-match counters. Cleared on MatchDestroyed.',
  ],
  [
    '_MatchAbandoned',
    'lifecycle',
    'match-started',
    '*',
    'provisional',
    '1.3',
    'MatchDestroyed arrived without a matching MatchEnded (ragequit, disconnect). RL counts this as a forfeit-loss; plugins should mirror that.',
  ],
  [
    '_StatfeedEvent',
    'stat',
    'stat-enriched',
    LR,
    'provisional',
    '1.1',
    'StatfeedEvent with MainTarget/SecondaryTarget pre-resolved. NOTE: fires for every Statfeed variant including those with dedicated promoted events (_Save, _Shot, _PlayerDemolished, …). Subscribing to both this and a promoted event sees the same Statfeed twice.',
    'statfeed:catchall',
  ],
  [
    '_BallHit',
    'play',
    'ballhit-enriched',
    ['live'],
    'provisional',
    '1.1',
    'BallHit with Players[] pre-resolved.',
  ],
  [
    '_CrossbarHit',
    'play',
    'crossbar-enriched',
    ['live'],
    'provisional',
    '1.1',
    'CrossbarHit with BallLastTouch.Player pre-resolved.',
  ],
  [
    '_MatchEnded',
    'lifecycle',
    'matchend-enriched',
    '*',
    'provisional',
    '1.1',
    'MatchEnded with winnerName + scoreBlue/scoreOrange resolved.',
  ],
  [
    '_GoalScored',
    'scoring',
    'goal-enriched',
    LR,
    'provisional',
    '1.1',
    'GoalScored with players resolved + scoringTeam/concedingTeam/isOwnGoal + modifiers.',
    'scoring',
  ],
  [
    '_OwnGoal',
    'scoring',
    'owngoal',
    LR,
    'provisional',
    '1.1',
    'Score-delta verified own goal. Higher confidence than _GoalScored.isOwnGoal.',
    'scoring',
  ],
  [
    '_PlayerDemolished',
    'stat',
    'demolish',
    LR,
    'provisional',
    '1.1',
    'Demolish with attacker/victim resolved + isSelfDemo/isTeamDemo flags + attackerSpeed/attackerWasSupersonic from the most recent UpdateState (SPECTATOR-only).',
    'statfeed:promoted',
  ],
  [
    '_FlipReset',
    'stat',
    'stat-simple',
    LR,
    'provisional',
    '1.1',
    'FlipReset with MainTarget resolved + flipResetsThisMatch counter.',
    'statfeed:promoted',
  ],
  [
    '_HatTrick',
    'stat',
    'stat-simple',
    LR,
    'provisional',
    '1.1',
    'HatTrick with MainTarget resolved + goalsThisMatch counter.',
    'statfeed:promoted',
  ],
  [
    '_Save',
    'stat',
    'save',
    LR,
    'provisional',
    '1.1',
    'Save with MainTarget resolved + correlatedShot.',
    'statfeed:promoted',
  ],
  [
    '_EpicSave',
    'stat',
    'save',
    LR,
    'provisional',
    '1.1',
    'EpicSave variant. Mutually exclusive with _Save on the wire.',
    'statfeed:promoted',
  ],
  [
    '_Shot',
    'stat',
    'shot',
    LR,
    'provisional',
    '1.1',
    'Shot with MainTarget resolved + correlatedTouch.',
    'statfeed:promoted',
  ],
  [
    '_Assist',
    'stat',
    'assist',
    LR,
    'provisional',
    '1.1',
    'Assist with MainTarget resolved + correlatedGoal.',
    'statfeed:promoted',
  ],
  [
    '_Center',
    'stat',
    'stat-touch',
    LR,
    'provisional',
    '1.1',
    'Center with MainTarget resolved + correlatedTouch.',
    'statfeed:promoted',
  ],
  [
    '_Clear',
    'stat',
    'stat-touch',
    LR,
    'provisional',
    '1.1',
    'Clear with MainTarget resolved + correlatedTouch.',
    'statfeed:promoted',
  ],
  [
    '_BicycleHit',
    'stat',
    'stat-touch',
    LR,
    'provisional',
    '1.1',
    'BicycleHit with MainTarget resolved + correlatedTouch.',
    'statfeed:promoted',
  ],
  [
    '_PlayerJoined',
    'roster',
    'player-event',
    '*',
    'provisional',
    '1.1',
    'Roster diff: player appeared this tick.',
  ],
  [
    '_PlayerLeft',
    'roster',
    'player-event',
    '*',
    'provisional',
    '1.1',
    'Roster diff: player disappeared this tick.',
  ],
  [
    '_PlayerScoreChanged',
    'stat',
    'score-delta',
    '*',
    'provisional',
    '1.1',
    'Per-player stat diff. Only fields that moved appear in delta.',
  ],
  [
    '_BoostPickup',
    'play',
    'boost-pickup',
    ['live'],
    'provisional',
    '1.1',
    'One event per physical boost pad pickup. Rising ticks from a single pad are coalesced; delta is the total gain.',
  ],
  [
    '_BoostConsumed',
    'play',
    'boost-consumed',
    ['live'],
    'provisional',
    '1.1',
    'Player Boost fell between ticks (not a respawn).',
  ],
  [
    '_BallPossessionChanged',
    'play',
    'possession',
    ['live'],
    'provisional',
    '1.1',
    'Game.Ball.TeamNum changed. before/after nullable.',
  ],
  [
    '_TeamScoreChanged',
    'scoring',
    'team-score-delta',
    LR,
    'provisional',
    '1.1',
    'A team Score moved. Fires alongside _GoalScored and _OwnGoal.',
    'scoring',
  ],
  [
    '_FirstTouch',
    'play',
    'first-touch',
    ['live'],
    'provisional',
    '1.1',
    'First BallHit after each RoundStarted. Re-arms every round.',
  ],
  [
    '_FirstBlood',
    'scoring',
    'first-blood',
    LR,
    'provisional',
    '1.1',
    'First _GoalScored of the match.',
  ],
  [
    '_OvertimeStarted',
    'lifecycle',
    'overtime-started',
    ['live'],
    'provisional',
    '1.1',
    'Rising edge of Game.bOvertime. Once per match.',
  ],
  [
    '_DemoChain',
    'stat',
    'demo-chain',
    LR,
    'provisional',
    '1.2',
    'Same attacker ≥2 demos within rolling 5s window.',
  ],
  [
    '_FastestShotOfMatch',
    'scoring',
    'fastest-shot',
    LR,
    'provisional',
    '1.2',
    'Per-match max ball speed surpassed.',
  ],
  [
    '_GoalReplayStarted',
    'replay',
    'goal-replay-context',
    '*',
    'provisional',
    '1.1',
    'Full _GoalScored payload on the bReplay rising edge.',
  ],
  [
    '_BootId',
    'lifecycle',
    'boot-id',
    '*',
    'stable',
    '1.0',
    'Process-lifetime ID; first SSE frame on every connect (framing-bypass).',
  ],
  [
    '_MatchState',
    'lifecycle',
    'match-state',
    '*',
    'stable',
    '2.0',
    'Authoritative gameplay state on every transition. Carries isFreeplay (no MatchCreated since the last MatchDestroyed and roster.length <= 1).',
  ],
  [
    '_IdentityChanged',
    'lifecycle',
    'identity',
    '*',
    'provisional',
    '2.0',
    'Backend-stored Identity (PrimaryID + Name) was Set or Cleared.',
  ],
  [
    '_SavedReplay',
    'replay',
    'saved-replay',
    '*',
    'provisional',
    '1.2',
    'User saved a .replay file from RL\'s post-match menu. Payload: matchGuid, fileName, path, sizeBytes, savedAt.',
  ],
  // Plumbing / framing events intentionally NOT cataloged — they
  // fire regardless of subscription filter and aren't gameplay:
  // _ConnectionStatus, _RosterChanged, _DevPluginReload,
  // _OverridesChanged, _SurfaceChanged, _StoreChanged. See the Go
  // catalog package doc and bus/framingSignals for details.
  [
    '_UnknownStatfeed',
    'stat',
    'unknown-statfeed',
    '*',
    'stable',
    '1.1',
    'Statfeed.EventName not in the verified registry.',
  ],
];

events.catalog = catalogData.map((row) => {
  const entry = {
    name: row[0],
    category: row[1],
    shape: row[2],
    livePhases: row[3],
    stability: row[4],
    since: row[5],
    desc: row[6],
  };
  if (row[7]) entry.subscriptionGroup = row[7];
  return Object.freeze(entry);
});
events.byCategory = events.catalog.reduce((acc, e) => {
  if (!acc[e.category]) acc[e.category] = [];
  acc[e.category].push(e.name);
  return acc;
}, {});
Object.freeze(events.catalog);
Object.freeze(events.byCategory);
